apiVersion: v1
kind: ConfigMap
metadata:
  name: lanchonete-pedido-configmap
  namespace: lanchonete-pedido
  labels:
    app: cm-postgres
data:
  PG_HOST: "terraform-20250211234040680300000003.czu4isocm08k.us-east-1.rds.amazonaws.com"