apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: lanchonete-pedido-hpa
  namespace: lanchonete-pedido
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: lanchonete-pedido-deployment
  minReplicas: 2
  maxReplicas: 10
  targetCPUUtilizationPercentage: 80