spring:
  profiles:
    active: ${springProfile:local}
  application:
    name: lanchonete-api-pedido
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/lanchonete_pedido  # Substituindo localhost por postgres-service
    username: lanchonete_pedido_user
    password: lanchonete_pedido_password
  flyway:
    enabled: true
server:
  servlet:
    context-path: /pedido
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always



