apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-configmap
  namespace: lanchonete-pedido
  labels:
    app: cm-postgres
data:
  postgres-dbname: "lanchonete_pedido"
  postgres_user: "lanchonete_pedido_user"