apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: lanchonete-pedido
  labels:
    app: sc-postgres
type: Opaque
data:
  password: bGFuY2hvbmV0ZV9wZWRpZG9fcGFzc3dvcmQ= # Base64 de 'lanchonete_pedido_password'